//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalsWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fmatch
    {
        public fmatch()
        {
            this.goals = new HashSet<goal>();
            this.matchevents = new HashSet<matchevent>();
        }
    
        public int id { get; set; }
        public System.DateTime matchDate { get; set; }
        public int seasonId { get; set; }
        public int homeTeamId { get; set; }
        public int awayTeamId { get; set; }
        public Nullable<int> winnerTeamId { get; set; }
        public Nullable<int> loserTeamId { get; set; }
        public string desc { get; set; }
        public string score { get; set; }
        public int homeTeamScore { get; set; }
        public int awayTeamScore { get; set; }
        public string info { get; set; }
        public int hasEvents { get; set; }
        public int hasStats { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateEventsAdded { get; set; }
    
        public virtual season season { get; set; }
        public virtual team homeTeam { get; set; }
        public virtual team awayTeam { get; set; }
        public virtual team winnerTeam { get; set; }
        public virtual team loserTeam { get; set; }
        public virtual ICollection<goal> goals { get; set; }
        public virtual ICollection<matchevent> matchevents { get; set; }
    }
}
