//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalsWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matchevent
    {
        public int id { get; set; }
        public int matchId { get; set; }
        public int index { get; set; }
        public int teamId { get; set; }
        public int minute { get; set; }
        public int second { get; set; }
        public int period { get; set; }
        public int expMinute { get; set; }
        public decimal x { get; set; }
        public decimal y { get; set; }
        public string type { get; set; }
        public bool success { get; set; }
        public int position { get; set; }
        public string flags { get; set; }
    
        public virtual fmatch fmatch { get; set; }
        public virtual team team { get; set; }
    }
}
