//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalsWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class season
    {
        public season()
        {
            this.fmatches = new HashSet<fmatch>();
            this.seasontables = new HashSet<seasontable>();
        }
    
        public int id { get; set; }
        public int tournamentid { get; set; }
        public string name { get; set; }
        public Nullable<int> championTeamId { get; set; }
        public Nullable<int> regionId { get; set; }
        public Nullable<int> year { get; set; }
        public string tableDesc { get; set; }
        public System.DateTime lastTableUpdate { get; set; }
    
        public virtual ICollection<fmatch> fmatches { get; set; }
        public virtual region region { get; set; }
        public virtual team championTeam { get; set; }
        public virtual tournament tournament { get; set; }
        public virtual ICollection<seasontable> seasontables { get; set; }
    }
}
